export { default as Welcome } from "./Welcome";
export { default as Favorites } from "./Favorites";
export { default as SignIn } from "./SignIn";
export { default as SignUp } from "./SignUp";
export { default as Home } from "./Home";
export { default as MovieDetail } from "./MovieDetail";
export { default as Movies } from "./Movies";
export { default as Rate } from "./Rate";
export { default as Profile } from "./Profile";
